require('dotenv').config();
const { Pool } = require('pg');

(async () => {
  const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
  const statements = [
    'ALTER TABLE conversations ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL',
    'ALTER TABLE sessions ADD COLUMN IF NOT EXISTS reject_reason VARCHAR(300) NULL',
    'ALTER TABLE sessions ADD COLUMN IF NOT EXISTS cancel_reason VARCHAR(300) NULL',
    'ALTER TABLE sessions ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ NULL',
    `CREATE TABLE IF NOT EXISTS conversation_payments (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      conversation_id BIGINT NOT NULL,
      student_id BIGINT NOT NULL,
      tutor_id BIGINT NOT NULL,
      amount NUMERIC(10,2) NULL,
      reference VARCHAR(150) NULL,
      status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected')),
      reject_reason VARCHAR(300) NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      reviewed_at TIMESTAMPTZ NULL,
      CONSTRAINT fk_convpayments_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
      CONSTRAINT fk_convpayments_student FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE,
      CONSTRAINT fk_convpayments_tutor FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE
    )`,
    'CREATE INDEX IF NOT EXISTS idx_convpayments_conversation ON conversation_payments (conversation_id, status)'
  ];
  try {
    for (const sql of statements) {
      await pool.query(sql);
      console.log('OK:', sql.slice(0, 60) + '...');
    }
  } catch (e) {
    console.error('MIGRATION FAILED:', e.message);
    process.exitCode = 1;
  }
  await pool.end();
})();
