-- ============================================================
-- reschema.sql
-- Idempotent schema + data update for EXISTING PeerLink databases.
-- Safe to re-run. Apply this in Supabase (SQL Editor) or via psql:
--
--   psql "$DATABASE_URL" -f database/reschema.sql
--
-- Fixes:
--   1. Adds the schema columns added after the initial deploy
--      (system messages, payment -> session linking, completion confirmations).
--   2. Backfills conversation_payments.session_id so sessions can resolve
--      their paid status again (payment_id was NULL in the UI).
--   3. Heals sessions that both sides confirmed under the old completion
--      logic but that never flipped to 'completed'.
--   4. Inserts the "Session Completed" system message into every completed
--      session's conversation so both sides see it in the chat.
--   5. Adds verification_status to tutor_profiles for tutor approval flow.
-- ============================================================

-- 1. MESSAGES — system messages are authored by the app, not a user
ALTER TABLE messages ALTER COLUMN sender_id DROP NOT NULL;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS is_system BOOLEAN NOT NULL DEFAULT FALSE;

-- 2. SESSIONS — per-side completion confirmations
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS student_complete_confirmed_at TIMESTAMPTZ NULL;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS tutor_complete_confirmed_at TIMESTAMPTZ NULL;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS learning_mode VARCHAR(20) NULL;

-- 3. CONVERSATION PAYMENTS — tie each payment to the exact session it paid for
ALTER TABLE conversation_payments ADD COLUMN IF NOT EXISTS session_id BIGINT NULL;
CREATE INDEX IF NOT EXISTS idx_convpayments_session ON conversation_payments (session_id);
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_convpayments_session'
  ) THEN
    ALTER TABLE conversation_payments
      ADD CONSTRAINT fk_convpayments_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE;
  END IF;
END $$;

-- 4. BACKFILL: attach orphaned payments to the session they were made for
-- (the most recent session in the same conversation that existed when paid)
UPDATE conversation_payments cp
SET session_id = (
  SELECT s.id FROM sessions s
  WHERE s.conversation_id = cp.conversation_id
    AND s.created_at <= cp.created_at
    AND s.status IN ('accepted','completed','cancelled')
  ORDER BY s.created_at DESC, s.id DESC
  LIMIT 1
)
WHERE cp.session_id IS NULL;

-- 5. HEAL: sessions where BOTH sides confirmed but the status stayed 'accepted'
-- (older completion logic never flipped the status on the second confirm)
UPDATE sessions
SET status = 'completed'
WHERE status = 'accepted'
  AND student_complete_confirmed_at IS NOT NULL
  AND tutor_complete_confirmed_at IS NOT NULL;

-- 6. TUTOR APPLICATIONS: storage for the tutor registration flow
CREATE TABLE IF NOT EXISTS tutor_applications (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name      VARCHAR(200) NOT NULL,
  email          VARCHAR(190) NOT NULL,
  phone          VARCHAR(30) NOT NULL,
  address        VARCHAR(255) NULL,
  hourly_rate    NUMERIC(10,2) NULL,
  subjects       JSONB NULL,
  license_number VARCHAR(100) NULL,
  institution    VARCHAR(200) NULL,
  specialization VARCHAR(200) NULL,
  years_teaching SMALLINT NULL,
  license_file   VARCHAR(255) NULL,
  id_file        VARCHAR(255) NULL,
  status         TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  reviewed_at    TIMESTAMPTZ NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_tutor_applications_status ON tutor_applications (status);
CREATE INDEX IF NOT EXISTS idx_tutor_applications_created ON tutor_applications (created_at);

-- 6. NOTIFY: post a "Session Completed" system message in the conversation of
-- every completed session that does not already have one
INSERT INTO messages (conversation_id, sender_id, body, is_system, is_read)
SELECT s.conversation_id, NULL, 'Session Completed', TRUE, TRUE
FROM sessions s
WHERE s.status = 'completed'
  AND s.conversation_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM messages m
    WHERE m.conversation_id = s.conversation_id
      AND m.is_system = TRUE
      AND m.body LIKE 'Session Completed%'
  );

-- 7. USER REPORTS — table for students/tutors to report other users
CREATE TABLE IF NOT EXISTS user_reports (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id     BIGINT NOT NULL,
  reported_id     BIGINT NOT NULL,
  reason          VARCHAR(100) NOT NULL,
  session_id      BIGINT NULL,
  details         TEXT NULL,
  status          TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','resolved')),
  action_taken    VARCHAR(50) NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at     TIMESTAMPTZ NULL,
  CONSTRAINT fk_user_reports_reporter FOREIGN KEY (reporter_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_user_reports_reported FOREIGN KEY (reported_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_user_reports_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE SET NULL,
  CONSTRAINT chk_not_self_report CHECK (reporter_id <> reported_id)
);
CREATE INDEX IF NOT EXISTS idx_user_reports_reporter ON user_reports (reporter_id);
CREATE INDEX IF NOT EXISTS idx_user_reports_reported ON user_reports (reported_id);
CREATE INDEX IF NOT EXISTS idx_user_reports_status ON user_reports (status);
CREATE INDEX IF NOT EXISTS idx_user_reports_created ON user_reports (created_at);

-- 8. TUTOR PROFILES — add verification_status for tutor approval flow
ALTER TABLE tutor_profiles ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('pending','approved','rejected'));

-- 9. CONVERSATION PAYMENTS — ensure reject_reason column exists for payment rejection tracking
ALTER TABLE conversation_payments ADD COLUMN IF NOT EXISTS reject_reason VARCHAR(300) NULL;

-- 10. PASSWORD RESET TOKENS — table for forgot password flow
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL,
  token_hash   VARCHAR(255) NOT NULL,
  expires_at   TIMESTAMPTZ NOT NULL,
  used_at      TIMESTAMPTZ NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_password_reset_user ON password_reset_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_token_hash ON password_reset_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_password_reset_expires ON password_reset_tokens (expires_at);

-- 11. USER MODERATION & WARNINGS
ALTER TABLE users ADD COLUMN IF NOT EXISTS suspended_until TIMESTAMPTZ NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS suspension_reason TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_banned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ban_reason TEXT NULL;

CREATE TABLE IF NOT EXISTS user_warnings (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL,
  admin_id        BIGINT NOT NULL,
  reason          TEXT NOT NULL,
  is_acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
  acknowledged_at TIMESTAMPTZ NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_user_warnings_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_user_warnings_admin FOREIGN KEY (admin_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_user_warnings_user ON user_warnings (user_id, is_acknowledged);