-- ============================================================
-- PeerLink - DATABASE RESET + RE-SEED (Supabase SQL Editor)
-- ------------------------------------------------------------
-- 1. Wipes ALL rows from every table (tables themselves are kept)
-- 2. Seeds ONLY the demo accounts with preset profiles:
--      Admin   : admin@peerlink.edu     (Admin@123)
--      Faculty : faculty@peerlink.edu   (Faculty@123)
--      Tutors  : maria@peerlink.edu     (Tutor@123)
--                gerome@peerlink.edu    (Tutor@123)
--                kiel@peerlink.edu      (Tutor@123)
--      Students: student@peerlink.edu   (Student@123)  [Juswa]
--                mike.chen@peerlink.edu (Student@123)
--    NO sessions, messages, conversations, matches,
--    evaluations or activity logs are seeded.
--    Add subjects/sessions from the app itself.
--
-- HOW TO USE: paste this whole file into the Supabase SQL Editor
-- and click RUN. Destructive: all existing data is deleted.
-- ============================================================

-- ------------------------------------------------------------
-- 0. SCHEMA UPDATE (safe, only creates what is missing)
-- Tutor subject addition requests (core of the request flow)
-- ------------------------------------------------------------
ALTER TABLE tutor_subjects ADD COLUMN IF NOT EXISTS rate_per_hour NUMERIC(10,2) NOT NULL DEFAULT 100;

-- Tutor rejection reason for session requests
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS reject_reason VARCHAR(300) NULL;

-- Student cancellation reason (5-minute free-cancel window)
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS cancel_reason VARCHAR(300) NULL;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ NULL;

-- Both-side completion confirmation (session completes only when both confirm)
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS student_complete_confirmed_at TIMESTAMPTZ NULL;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS tutor_complete_confirmed_at TIMESTAMPTZ NULL;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS learning_mode VARCHAR(20) NULL;

-- Profile contact number and gender (Profile tab edit form)
ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS contact_no VARCHAR(20) NULL;
ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS gender VARCHAR(20) NULL;
ALTER TABLE tutor_profiles ADD COLUMN IF NOT EXISTS contact_no VARCHAR(20) NULL;
ALTER TABLE tutor_profiles ADD COLUMN IF NOT EXISTS gender VARCHAR(20) NULL;

-- Tutor verification status (for approval flow)
ALTER TABLE tutor_profiles ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('pending','approved','rejected'));

-- Password reset tokens (for forgot password flow)
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL,
  token_hash   VARCHAR(255) NOT NULL,
  expires_at   TIMESTAMPTZ NOT NULL,
  used_at      TIMESTAMPTZ NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_password_reset_user ON password_reset_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_token_hash ON password_reset_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_password_reset_expires ON password_reset_tokens (expires_at);

CREATE TABLE IF NOT EXISTS user_reports (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id     BIGINT NOT NULL,
  reported_id     BIGINT NOT NULL,
  reason          VARCHAR(100) NOT NULL,
  session_id      BIGINT NULL,
  details         TEXT NULL,
  status          TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','resolved')),
  action_taken    VARCHAR(50) NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at     TIMESTAMPTZ NULL,
  CONSTRAINT fk_user_reports_reporter FOREIGN KEY (reporter_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_user_reports_reported FOREIGN KEY (reported_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_user_reports_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE SET NULL,
  CONSTRAINT chk_not_self_report CHECK (reporter_id <> reported_id)
);
CREATE INDEX IF NOT EXISTS idx_user_reports_reporter ON user_reports (reporter_id);
CREATE INDEX IF NOT EXISTS idx_user_reports_reported ON user_reports (reported_id);
CREATE INDEX IF NOT EXISTS idx_user_reports_status ON user_reports (status);
CREATE INDEX IF NOT EXISTS idx_user_reports_created ON user_reports (created_at);

CREATE TABLE IF NOT EXISTS reschedule_requests (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id     BIGINT NOT NULL,
  requester_id   BIGINT NOT NULL,
  proposed_start TIMESTAMPTZ NOT NULL,
  proposed_end   TIMESTAMPTZ NOT NULL,
  reason         VARCHAR(500) NULL,
  status         TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  responded_at   TIMESTAMPTZ NULL,
  CONSTRAINT fk_reschedule_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,
  CONSTRAINT fk_reschedule_requester FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_reschedule_end CHECK (proposed_end > proposed_start)
);
CREATE INDEX IF NOT EXISTS idx_reschedule_session_status ON reschedule_requests (session_id, status);

CREATE TABLE IF NOT EXISTS resources (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_id   BIGINT NOT NULL,
  subject_id BIGINT NULL,
  title      VARCHAR(255) NOT NULL,
  file_name  VARCHAR(255) NULL,
  file_type  VARCHAR(20) NOT NULL DEFAULT 'PDF',
  size_bytes BIGINT NULL,
  description TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_resources_tutor FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_resources_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_resources_tutor ON resources (tutor_id);
CREATE INDEX IF NOT EXISTS idx_resources_subject ON resources (subject_id);

ALTER TABLE resources ADD COLUMN IF NOT EXISTS file_name VARCHAR(255) NULL;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS description TEXT NULL;

CREATE TABLE IF NOT EXISTS conversations (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  tutor_id   BIGINT NOT NULL,
  subject_id BIGINT NULL,
  deleted_by BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_conversations_student FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_conversations_tutor FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_conversations_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE,
  CONSTRAINT uq_conversation_participants UNIQUE (student_id, tutor_id, subject_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_conversation_no_subject ON conversations (student_id, tutor_id) WHERE subject_id IS NULL;

-- Profile-initiated chats have no subject.
ALTER TABLE conversations ALTER COLUMN subject_id DROP NOT NULL;

-- Self-side delete (each participant hides the conversation only for themselves;
-- if both delete, the row is pruned by the backend).
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL;

CREATE TABLE IF NOT EXISTS messages (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  sender_id       BIGINT NOT NULL,
  body            TEXT NOT NULL,
  is_read         BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
  CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages (conversation_id, created_at);

-- System messages (e.g. "Session Completed") are authored by the app, not a user,
-- so they have no sender and are rendered as a centered system notice.
ALTER TABLE messages ALTER COLUMN sender_id DROP NOT NULL;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS is_system BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS conversation_payments (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  session_id      BIGINT NULL,
  student_id      BIGINT NOT NULL,
  tutor_id        BIGINT NOT NULL,
  amount          NUMERIC(10,2) NULL,
  reference       VARCHAR(150) NULL,
  status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected')),
  reject_reason   VARCHAR(300) NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at     TIMESTAMPTZ NULL,
  CONSTRAINT fk_convpayments_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
  CONSTRAINT fk_convpayments_student FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_convpayments_tutor FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_convpayments_conversation ON conversation_payments (conversation_id, status);

-- Payments are tied to the exact session they paid for, so a cancelled booking's
-- payment never carries over to a new booking in the same conversation.
ALTER TABLE conversation_payments ADD COLUMN IF NOT EXISTS session_id BIGINT NULL;
CREATE INDEX IF NOT EXISTS idx_convpayments_session ON conversation_payments (session_id);
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_convpayments_session'
  ) THEN
    ALTER TABLE conversation_payments
      ADD CONSTRAINT fk_convpayments_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE;
  END IF;
END $$;

-- Best-effort backfill for payments created before this migration: attach each
-- payment to the most recent session in the same conversation that existed when
-- the payment was made.
UPDATE conversation_payments cp
SET session_id = (
  SELECT s.id FROM sessions s
  WHERE s.conversation_id = cp.conversation_id
    AND s.created_at <= cp.created_at
    AND s.status IN ('accepted','completed','cancelled')
  ORDER BY s.created_at DESC, s.id DESC
  LIMIT 1
)
WHERE cp.session_id IS NULL;

-- Heal sessions where both sides confirmed completion under the old logic but
-- the status never flipped to 'completed'.
UPDATE sessions
SET status = 'completed'
WHERE status = 'accepted'
  AND student_complete_confirmed_at IS NOT NULL
  AND tutor_complete_confirmed_at IS NOT NULL;

-- Post a "Session Completed" system message in the conversation of every
-- completed session that does not already have one.
INSERT INTO messages (conversation_id, sender_id, body, is_system, is_read)
SELECT s.conversation_id, NULL, 'Session Completed', TRUE, TRUE
FROM sessions s
WHERE s.status = 'completed'
  AND s.conversation_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM messages m
    WHERE m.conversation_id = s.conversation_id
      AND m.is_system = TRUE
      AND m.body LIKE 'Session Completed%'
  );

CREATE TABLE IF NOT EXISTS subject_requests (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_id      BIGINT NOT NULL,
  code          VARCHAR(20) NOT NULL,
  name          VARCHAR(150) NOT NULL,
  description   TEXT NULL,
  proficiency   SMALLINT NOT NULL DEFAULT 3,
  strand        VARCHAR(20) NULL,
  status        TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at   TIMESTAMPTZ NULL,
  CONSTRAINT uq_subject_request UNIQUE (tutor_id, code),
  CONSTRAINT fk_subject_requests_tutor FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_subject_request_proficiency CHECK (proficiency BETWEEN 1 AND 5)
);

-- Strand tagging on the subjects catalog and requests
-- (safe no-ops when the columns already exist)
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS strand VARCHAR(20) NULL;
ALTER TABLE subject_requests ADD COLUMN IF NOT EXISTS strand VARCHAR(20) NULL;

-- ------------------------------------------------------------
-- 1. WIPE EVERYTHING
-- ------------------------------------------------------------
TRUNCATE TABLE activity_logs, evaluations, payments, sessions, messages, conversations,
             conversation_payments, matches, tutor_subjects, student_subjects, subjects,
             tutor_profiles, student_profiles, users, subject_requests, user_reports,
             password_reset_tokens
       RESTART IDENTITY CASCADE;

-- Prevent a student booking the same tutor for the same subject twice
-- (created after the wipe so leftover active sessions cannot break it)
CREATE UNIQUE INDEX IF NOT EXISTS uq_sessions_active_booking ON sessions (student_id, tutor_id, subject_id) WHERE status IN ('pending','accepted');

-- ------------------------------------------------------------
-- 2. USERS (7 demo accounts — passwords Tutor@123 / Student@123)
-- ------------------------------------------------------------
INSERT INTO users (id, email, password_hash, first_name, last_name, role, is_active) VALUES
(1, 'admin@peerlink.edu',     '$2a$10$vvDNXhEYATRXuM6NXzQW.eweNMp6/DT4iri5L6FyLcQG3ZUHzijgi', 'Alex',    'Admin',    'admin',   TRUE),
(2, 'faculty@peerlink.edu',   '$2a$10$JDusT272YLpZvBJ/CRJM0u0NnxGraIk0QqtNtms78LYSJzTipY56i', 'Dana',    'Faculty',  'faculty', TRUE),
(3, 'maria@peerlink.edu',     '$2a$10$oqZpYzmn5EjTMD0mpfSbk.3YFAsP3MU.zcgnc8ozv2P8qMKam7h5u', 'Maria',   'Tutor',    'tutor',   TRUE),
(4, 'student@peerlink.edu',   '$2a$10$sxsfR9PejLT4wmo1A6i2Uer0XPVLGpd2RGZD6ptBm2lB9HBQ8Vt8K', 'Juswa',   'Student',  'student', TRUE),
(5, 'gerome@peerlink.edu',    '$2a$10$oqZpYzmn5EjTMD0mpfSbk.3YFAsP3MU.zcgnc8ozv2P8qMKam7h5u', 'Gerome',  'Sanchez',  'tutor',   TRUE),
(6, 'kiel@peerlink.edu',      '$2a$10$oqZpYzmn5EjTMD0mpfSbk.3YFAsP3MU.zcgnc8ozv2P8qMKam7h5u', 'Kiel',    'Reyes',    'tutor',   TRUE),
(7, 'mike.chen@peerlink.edu', '$2a$10$sxsfR9PejLT4wmo1A6i2Uer0XPVLGpd2RGZD6ptBm2lB9HBQ8Vt8K', 'Mike',    'Chen',     'student', TRUE);

-- ------------------------------------------------------------
-- 3. STUDENT PROFILES (preset, based on the existing data)
-- ------------------------------------------------------------
INSERT INTO student_profiles (id, user_id, year_level, course, bio) VALUES
(1, 4, 2, 'Computer Science', 'Second year CS student looking for help with math and programming.'),
(2, 7, 1, 'Computer Science', 'Freshman CS student, struggling with calculus.');

-- ------------------------------------------------------------
-- 4. TUTOR PROFILES (preset availability and bios)
-- ------------------------------------------------------------
INSERT INTO tutor_profiles (id, user_id, course, max_year_level, bio, availability, verification_status) VALUES
(1, 3, 'Computer Science', 4, 'Senior CS student. Strong in math and programming, patient with beginners.', '{"Mon":["09:00-12:00","15:00-17:00"],"Tue":["10:00-13:00"],"Wed":["09:00-11:00","14:00-16:00"],"Thu":["10:00-12:00"],"Fri":["09:00-12:00"]}', 'pending'),
(2, 5, 'Mathematics', 5, 'History and mathematics tutor. Clear, structured review sessions with guides.', '{"Mon":["09:00-11:00"],"Tue":["14:00-17:00"],"Wed":["09:00-11:00","15:00-17:00"],"Thu":["14:00-16:00"],"Fri":["13:00-17:00"]}', 'approved'),
(3, 6, 'Networking', 5, 'Networking specialist. TCP/IP, routing, and subnetting made simple.', '{"Mon":["13:00-16:00"],"Tue":["09:00-11:00"],"Wed":["13:00-15:00"],"Thu":["15:00-17:00"],"Fri":["09:00-12:00"]}', 'pending');

-- ------------------------------------------------------------
-- 5. SUBJECTS CATALOG (presets per strand — STEM, ICT, ABM,
--      HUMSS, GAS, General). strand = NULL means a general /
--      core subject available to every strand. Students pick
--      from these; tutors are assigned preset subjects in
--      section 6.
-- ------------------------------------------------------------
INSERT INTO subjects (id, code, name, description, strand) VALUES
-- General / core (available to all strands)
(1,  'MATH101', 'Calculus I',                     'Limits, derivatives, and integrals of single-variable functions.', 'STEM'),
(2,  'MATH210', 'Linear Algebra',                 'Vectors, matrices, eigenvalues, and linear transformations.', 'STEM'),
(3,  'CS220',   'Data Structures',                'Stacks, queues, trees, graphs, and algorithmic analysis.', 'ICT'),
(4,  'CS330',   'Web Development',                'HTML, CSS, JavaScript, and modern web frameworks.', 'ICT'),
(5,  'ENG110',  'English Composition',            'Academic writing, essays, and research papers.', NULL),
(6,  'PHYS101', 'Physics I',                      'Mechanics: kinematics, forces, energy, and momentum.', 'STEM'),
(7,  'CS240',   'Database Systems',               'SQL, database design, normalization, and transactions.', 'ICT'),
(8,  'STAT150', 'Statistics',                     'Descriptive statistics, probability, and hypothesis testing.', NULL),
(9,  'HIST101', 'History',                        'World history, Philippine history, and social studies.', 'HUMSS'),
(10, 'NET101',  'Computer Networking',            'OSI model, TCP/IP, routing, and network configuration.', 'ICT'),
(11, 'PRG101',  'Programming Fundamentals',       'Logic, control structures, functions, and problem solving.', 'ICT'),
(12, 'BIO101',  'Biology',                        'Cell biology, genetics, and human anatomy.', 'STEM'),
(13, 'CS230',   'Embedded Systems',               'Microcontrollers, sensors, and embedded C programming.', 'ICT'),
(14, 'GEN101',  'Oral Communication',             'Speech, listening and interpersonal communication skills.', NULL),
(15, 'GEN102',  'Reading and Writing',            'Critical reading strategies and academic writing skills.', NULL),
(16, 'GEN103',  'Filipino Language and Literature','Komunikasyon at pananaliksik sa wika at kulturang Filipino.', NULL),
(17, 'GEN104',  '21st Century Literature',        'Literature from the Philippines and around the world.', NULL),
(18, 'GEN105',  'Contemporary Philippine Arts',   'Contemporary art forms and practices from the regions.', NULL),
(19, 'GEN106',  'Media and Information Literacy', 'Understanding media, information sources, and digital literacy.', NULL),
(20, 'GEN107',  'General Mathematics',            'Functions, logarithms, business math and logic.', NULL),
(21, 'GEN109',  'Earth and Life Science',         'Earth systems, geology, and life processes.', NULL),
(22, 'GEN110',  'Physical Science',               'Chemistry and physics concepts in everyday life.', NULL),
(23, 'GEN111',  'Personal Development',           'Self-awareness, emotional intelligence, and career planning.', NULL),
(24, 'GEN112',  'Understanding Culture, Society and Politics', 'Culture, society, and political structures.', NULL),
(25, 'GEN113',  'Introduction to the Philosophy of the Human Person', 'Philosophical reflection on human existence.', NULL),
(26, 'GEN114',  'Physical Education and Health',  'Fitness, sports, and healthy lifestyle practices.', NULL),
(27, 'GEN115',  'Practical Research 1',           'Qualitative research methods and writing.', NULL),
(28, 'GEN116',  'Practical Research 2',           'Quantitative research methods and statistical treatment.', NULL),
(29, 'GEN117',  'Inquiries, Investigation and Immersion', 'Immersive research experience and reporting.', NULL),
(30, 'GEN118',  'Empowerment Technologies',       'ICT tools, productivity software, and online safety.', NULL),
(31, 'GEN119',  'Entrepreneurship',               'Business idea development and small business planning.', NULL),
-- STEM specialized
(32, 'STEM09',  'Pre-Calculus',                   'Trigonometry, conic sections, and series.', 'STEM'),
(33, 'STEM10',  'Basic Calculus',                 'Limits, derivatives and integrals in the SHS curriculum.', 'STEM'),
(34, 'STEM11',  'General Biology 1',              'Cell biology and life processes.', 'STEM'),
(35, 'STEM12',  'General Chemistry 1',            'Atomic structure, chemical bonding, and stoichiometry.', 'STEM'),
(36, 'STEM13',  'General Chemistry 2',            'Thermodynamics, kinetics, and organic chemistry.', 'STEM'),
(37, 'STEM14',  'General Physics 1',              'Mechanics, waves, and heat.', 'STEM'),
(38, 'STEM15',  'General Physics 2',              'Electricity, magnetism, optics, and modern physics.', 'STEM'),
(39, 'STEM16',  'Research Project / Capstone',    'Independent STEM research culminating in a capstone project.', 'STEM'),
-- ABM specialized
(40, 'ABM01',   'Organization and Management',    'Management theories, functions, and organizational structures.', 'ABM'),
(41, 'ABM02',   'Business Mathematics',           'Profit and loss, ratios, and business computations.', 'ABM'),
(42, 'ABM03',   'Principles of Marketing',        'Marketing concepts, consumer behavior, and branding.', 'ABM'),
(43, 'ABM04',   'Fundamentals of Accountancy, Business and Management 1', 'Accounting basics, journal entries, and financial statements.', 'ABM'),
(44, 'ABM05',   'Fundamentals of Accountancy, Business and Management 2', 'Advanced accounting cycles and business management.', 'ABM'),
(45, 'ABM06',   'Applied Economics',              'Economic principles applied to current issues.', 'ABM'),
(46, 'ABM07',   'Business Ethics and Social Responsibility', 'Ethical decision-making in business.', 'ABM'),
(47, 'ABM08',   'Business Finance',               'Financial management, risk, and investment basics.', 'ABM'),
-- HUMSS specialized
(48, 'HUMSS01', 'Philippine Politics and Governance', 'Philippine government structure and political dynamics.', 'HUMSS'),
(49, 'HUMSS02', 'Trends, Networks, and Critical Thinking', 'Trend analysis, networks, and critical thinking skills.', 'HUMSS'),
(50, 'HUMSS03', 'Community Engagement, Solidarity and Citizenship', 'Community dynamics and civic participation.', 'HUMSS'),
(51, 'HUMSS04', 'Discipline and Ideas in the Social Sciences', 'Foundations of the social science disciplines.', 'HUMSS'),
(52, 'HUMSS05', 'Disciplines and Ideas in the Applied Social Sciences', 'Applied fields: counseling, social work, and communication.', 'HUMSS'),
(53, 'HUMSS06', 'Creative Writing',               'Poetry, fiction, and drama writing practice.', 'HUMSS'),
(54, 'HUMSS07', 'Creative Nonfiction',            'Literary journalism, memoir, and personal essays.', 'HUMSS'),
(55, 'HUMSS08', 'Introduction to World Religions and Belief Systems', 'Comparative study of major world religions.', 'HUMSS'),
-- GAS specialized
(56, 'GAS01',   'Earth Science',                  'Geology, meteorology, and environmental science.', 'GAS'),
(57, 'GAS02',   'Economics',                      'Microeconomics, macroeconomics, and economic systems.', 'GAS'),
(58, 'GAS03',   'English for Academic and Professional Purposes', 'Academic language and workplace communication.', 'GAS'),
-- ICT specialized
(59, 'ICT01',   'Computer System Servicing',      'Hardware assembly, maintenance, and system configuration.', 'ICT'),
(60, 'ICT02',   'Animation',                      '2D/3D animation principles and production.', 'ICT');

-- ------------------------------------------------------------
-- 6. TUTOR SUBJECTS (PRESET "Subjects I Teach" — tutors cannot
--      change this list themselves; they may only REQUEST a new
--      subject, which an admin approves and assigns here)
--   Maria   (tutor profile 1) : Calculus I 5, Data Structures 5, English Composition 4
--   Gerome  (tutor profile 2) : Calculus I 4, History 5
--   Kiel    (tutor profile 3) : Computer Networking 5
-- ------------------------------------------------------------
INSERT INTO tutor_subjects (tutor_profile_id, subject_id, proficiency) VALUES
(1, 1, 5), (1, 3, 5), (1, 5, 4),
(2, 1, 4), (2, 9, 5),
(3, 10, 5);

-- ------------------------------------------------------------
-- 7. RESET SEQUENCES
-- ------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('users', 'id'), (SELECT MAX(id) FROM users));
SELECT setval(pg_get_serial_sequence('student_profiles', 'id'), (SELECT MAX(id) FROM student_profiles));
SELECT setval(pg_get_serial_sequence('tutor_profiles', 'id'), (SELECT MAX(id) FROM tutor_profiles));
SELECT setval(pg_get_serial_sequence('subjects', 'id'), (SELECT MAX(id) FROM subjects));
SELECT setval(pg_get_serial_sequence('tutor_subjects', 'id'), (SELECT MAX(id) FROM tutor_subjects));

-- Done. All business data (sessions, messages, subjects, ...) is empty.