-- ============================================================
-- PeerLink - Peer Tutoring Platform
-- Supabase (PostgreSQL) Schema + Seed Data
-- Normalized 4-tier architecture database layer
--
-- HOW TO USE: create a Supabase project, open the SQL Editor,
-- paste this whole file and run it. It creates all tables in
-- the default `public` schema plus demo seed data.
-- ============================================================

-- Drop in dependency order so the script is re-runnable.
DROP TABLE IF EXISTS activity_logs CASCADE;
DROP TABLE IF EXISTS evaluations CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS conversations CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS tutor_subjects CASCADE;
DROP TABLE IF EXISTS student_subjects CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS tutor_profiles CASCADE;
DROP TABLE IF EXISTS student_profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Mimics MySQL's ON UPDATE CURRENT_TIMESTAMP for updated_at columns.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- USERS
-- ------------------------------------------------------------
CREATE TABLE users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         VARCHAR(190) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  first_name    VARCHAR(100) NOT NULL,
  last_name     VARCHAR(100) NOT NULL,
  role          TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student','tutor','faculty','admin')),
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_users_email UNIQUE (email)
);
CREATE INDEX idx_users_role ON users (role);
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- STUDENT PROFILES
-- ------------------------------------------------------------
CREATE TABLE student_profiles (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL,
  year_level SMALLINT NULL,
  course     VARCHAR(150) NULL,
  bio        TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_student_user UNIQUE (user_id),
  CONSTRAINT fk_student_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE TRIGGER trg_student_profiles_updated_at BEFORE UPDATE ON student_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- TUTOR PROFILES
-- Availability stored as JSONB: {"Mon":["09:00-11:00"],"Tue":[...]}
-- ------------------------------------------------------------
CREATE TABLE tutor_profiles (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT NOT NULL,
  course         VARCHAR(150) NULL,
  max_year_level SMALLINT NOT NULL DEFAULT 5,
  bio            TEXT NULL,
  availability   JSONB NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_tutor_user UNIQUE (user_id),
  CONSTRAINT fk_tutor_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE TRIGGER trg_tutor_profiles_updated_at BEFORE UPDATE ON tutor_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- SUBJECTS
-- ------------------------------------------------------------
CREATE TABLE subjects (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        VARCHAR(20) NOT NULL,
  name        VARCHAR(150) NOT NULL,
  description TEXT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_subjects_code UNIQUE (code)
);
CREATE TRIGGER trg_subjects_updated_at BEFORE UPDATE ON subjects FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- STUDENT SUBJECTS (subjects a student needs help with)
-- ------------------------------------------------------------
CREATE TABLE student_subjects (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_profile_id BIGINT NOT NULL,
  subject_id         BIGINT NOT NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_student_subject UNIQUE (student_profile_id, subject_id),
  CONSTRAINT fk_student_subjects_profile FOREIGN KEY (student_profile_id) REFERENCES student_profiles (id) ON DELETE CASCADE,
  CONSTRAINT fk_student_subjects_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE
);
CREATE INDEX idx_student_subjects_subject ON student_subjects (subject_id);

-- ------------------------------------------------------------
-- TUTOR SUBJECTS (subjects a tutor teaches + proficiency 1-5)
-- ------------------------------------------------------------
CREATE TABLE tutor_subjects (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_profile_id BIGINT NOT NULL,
  subject_id       BIGINT NOT NULL,
  proficiency      SMALLINT NOT NULL DEFAULT 3, -- 1-5
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_tutor_subject UNIQUE (tutor_profile_id, subject_id),
  CONSTRAINT fk_tutor_subjects_profile FOREIGN KEY (tutor_profile_id) REFERENCES tutor_profiles (id) ON DELETE CASCADE,
  CONSTRAINT fk_tutor_subjects_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE,
  CONSTRAINT chk_tutor_proficiency CHECK (proficiency BETWEEN 1 AND 5)
);
CREATE INDEX idx_tutor_subjects_subject ON tutor_subjects (subject_id);

-- ------------------------------------------------------------
-- MATCHES (compatibility results, 0-100)
-- ------------------------------------------------------------
CREATE TABLE matches (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_profile_id   BIGINT NOT NULL,
  tutor_profile_id     BIGINT NOT NULL,
  subject_id           BIGINT NOT NULL,
  compatibility_score  NUMERIC(5,2) NOT NULL,
  score_breakdown      JSONB NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_match UNIQUE (student_profile_id, tutor_profile_id, subject_id),
  CONSTRAINT fk_matches_student FOREIGN KEY (student_profile_id) REFERENCES student_profiles (id) ON DELETE CASCADE,
  CONSTRAINT fk_matches_tutor FOREIGN KEY (tutor_profile_id) REFERENCES tutor_profiles (id) ON DELETE CASCADE,
  CONSTRAINT fk_matches_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE
);
CREATE INDEX idx_matches_student_score ON matches (student_profile_id, compatibility_score);

-- ------------------------------------------------------------
-- CONVERSATIONS (between a student user and a tutor user on a subject)
-- ------------------------------------------------------------
CREATE TABLE conversations (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  tutor_id   BIGINT NOT NULL,
  subject_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_conversation UNIQUE (student_id, tutor_id, subject_id),
  CONSTRAINT fk_conversations_student FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_conversations_tutor FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_conversations_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE
);
CREATE INDEX idx_conversations_tutor ON conversations (tutor_id);
CREATE TRIGGER trg_conversations_updated_at BEFORE UPDATE ON conversations FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- MESSAGES
-- ------------------------------------------------------------
CREATE TABLE messages (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  sender_id       BIGINT NOT NULL,
  body            TEXT NOT NULL,
  is_read         BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
  CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_messages_conversation ON messages (conversation_id, created_at);
CREATE INDEX idx_messages_sender ON messages (sender_id);

-- ------------------------------------------------------------
-- SESSIONS (tutoring sessions, full workflow)
-- ------------------------------------------------------------
CREATE TABLE sessions (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id      BIGINT NOT NULL,
  tutor_id        BIGINT NOT NULL,
  subject_id      BIGINT NOT NULL,
  conversation_id BIGINT NULL,
  status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected','cancelled','completed')),
  scheduled_start TIMESTAMPTZ NOT NULL,
  scheduled_end   TIMESTAMPTZ NOT NULL,
  topic           VARCHAR(255) NULL,
  notes           TEXT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_sessions_student FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_sessions_tutor FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_sessions_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE,
  CONSTRAINT fk_sessions_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE SET NULL,
  CONSTRAINT chk_sessions_end CHECK (scheduled_end > scheduled_start)
);
CREATE INDEX idx_sessions_tutor_time ON sessions (tutor_id, status, scheduled_start);
CREATE INDEX idx_sessions_student_time ON sessions (student_id, scheduled_start);
CREATE INDEX idx_sessions_subject ON sessions (subject_id);
CREATE TRIGGER trg_sessions_updated_at BEFORE UPDATE ON sessions FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- EVALUATIONS (one per completed session)
-- ------------------------------------------------------------
CREATE TABLE evaluations (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  tutor_id   BIGINT NOT NULL,
  rating     SMALLINT NOT NULL,
  comment    TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_evaluation_session UNIQUE (session_id),
  CONSTRAINT fk_evaluations_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,
  CONSTRAINT fk_evaluations_student FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_evaluations_tutor FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_evaluation_rating CHECK (rating BETWEEN 1 AND 5)
);
CREATE INDEX idx_evaluations_tutor ON evaluations (tutor_id);

-- ------------------------------------------------------------
-- ACTIVITY LOGS
-- ------------------------------------------------------------
CREATE TABLE activity_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NULL,
  action      VARCHAR(100) NOT NULL,
  entity_type VARCHAR(50) NULL,
  entity_id   BIGINT NULL,
  details     JSONB NULL,
  ip_address  VARCHAR(45) NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_logs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX idx_logs_user ON activity_logs (user_id);
CREATE INDEX idx_logs_action ON activity_logs (action);
CREATE INDEX idx_logs_created ON activity_logs (created_at);

-- ============================================================
-- SEED DATA
-- Default passwords: Admin@123 / Faculty@123 / Tutor@123 / Student@123
-- Hashes generated with bcryptjs (cost 10)
-- ============================================================

INSERT INTO users (id, email, password_hash, first_name, last_name, role, is_active) VALUES
(1, 'admin@peerlink.edu', '$2a$10$vvDNXhEYATRXuM6NXzQW.eweNMp6/DT4iri5L6FyLcQG3ZUHzijgi', 'Alex', 'Admin', 'admin', TRUE),
(2, 'faculty@peerlink.edu', '$2a$10$JDusT272YLpZvBJ/CRJM0u0NnxGraIk0QqtNtms78LYSJzTipY56i', 'Dana', 'Faculty', 'faculty', TRUE),
(3, 'tutor@peerlink.edu', '$2a$10$oqZpYzmn5EjTMD0mpfSbk.3YFAsP3MU.zcgnc8ozv2P8qMKam7h5u', 'Maria', 'Tutor', 'tutor', TRUE),
(4, 'student@peerlink.edu', '$2a$10$sxsfR9PejLT4wmo1A6i2Uer0XPVLGpd2RGZD6ptBm2lB9HBQ8Vt8K', 'John', 'Student', 'student', TRUE),
(5, 'david.garcia@peerlink.edu', '$2a$10$oqZpYzmn5EjTMD0mpfSbk.3YFAsP3MU.zcgnc8ozv2P8qMKam7h5u', 'David', 'Garcia', 'tutor', TRUE),
(6, 'sara.kim@peerlink.edu', '$2a$10$oqZpYzmn5EjTMD0mpfSbk.3YFAsP3MU.zcgnc8ozv2P8qMKam7h5u', 'Sara', 'Kim', 'tutor', TRUE),
(7, 'mike.chen@peerlink.edu', '$2a$10$sxsfR9PejLT4wmo1A6i2Uer0XPVLGpd2RGZD6ptBm2lB9HBQ8Vt8K', 'Mike', 'Chen', 'student', TRUE);

INSERT INTO student_profiles (id, user_id, year_level, course, bio) VALUES
(1, 4, 2, 'Computer Science', 'Second year CS student looking for help with math and programming.'),
(2, 7, 1, 'Computer Science', 'Freshman CS student, struggling with calculus.');

INSERT INTO tutor_profiles (id, user_id, course, max_year_level, bio, availability) VALUES
(1, 3, 'Computer Science', 4, 'Senior CS student. Strong in math and programming, patient with beginners.', '{"Mon":["09:00-12:00","15:00-17:00"],"Tue":["10:00-13:00"],"Wed":["09:00-11:00","14:00-16:00"],"Thu":["10:00-12:00"],"Fri":["09:00-12:00"]}'),
(2, 5, 'Mathematics', 5, 'Math major, excellent at calculus and statistics. Offers structured lessons.', '{"Mon":["08:00-10:00"],"Tue":["08:00-10:00","13:00-15:00"],"Wed":["10:00-12:00"],"Thu":["09:00-11:00"],"Fri":["13:00-17:00"]}'),
(3, 6, 'Computer Science', 3, 'Third year CS student, web development and database systems enthusiast.', '{"Mon":["13:00-15:00"],"Tue":["15:00-17:00"],"Wed":["15:00-17:00"],"Thu":["13:00-15:00"],"Sat":["10:00-14:00"]}');

INSERT INTO subjects (id, code, name, description) VALUES
(1, 'MATH101', 'Calculus I', 'Limits, derivatives, and integrals of single-variable functions.'),
(2, 'MATH210', 'Linear Algebra', 'Vectors, matrices, eigenvalues, and linear transformations.'),
(3, 'CS220', 'Data Structures', 'Stacks, queues, trees, graphs, and algorithmic analysis.'),
(4, 'CS330', 'Web Development', 'HTML, CSS, JavaScript, and modern web frameworks.'),
(5, 'ENG110', 'English Composition', 'Academic writing, essays, and research papers.'),
(6, 'PHYS101', 'Physics I', 'Mechanics: kinematics, forces, energy, and momentum.'),
(7, 'CS240', 'Database Systems', 'SQL, database design, normalization, and transactions.'),
(8, 'STAT150', 'Statistics', 'Descriptive statistics, probability, and hypothesis testing.');

INSERT INTO student_subjects (student_profile_id, subject_id) VALUES
(1, 1), (1, 3), (1, 5), (2, 1), (2, 6);

INSERT INTO tutor_subjects (tutor_profile_id, subject_id, proficiency) VALUES
(1, 1, 5), (1, 3, 5), (1, 5, 4), (2, 1, 4), (2, 8, 5), (3, 4, 5), (3, 7, 4);

INSERT INTO matches (student_profile_id, tutor_profile_id, subject_id, compatibility_score, score_breakdown) VALUES
(1, 1, 1, 92.00, '{"subject":40,"proficiency":20,"course_year":10,"availability":12,"rating":10}'),
(1, 2, 1, 87.00, '{"subject":40,"proficiency":16,"course_year":15,"availability":11,"rating":5}'),
(2, 1, 1, 88.00, '{"subject":40,"proficiency":20,"course_year":10,"availability":13,"rating":5}');

INSERT INTO conversations (id, student_id, tutor_id, subject_id) VALUES
(1, 4, 3, 1),
(2, 4, 3, 3);

INSERT INTO messages (conversation_id, sender_id, body, is_read) VALUES
(1, 4, 'Hi Maria! I need help understanding derivatives for my upcoming exam. Do you have time this week?', TRUE),
(1, 3, 'Hi John! Sure, I would love to help. I am free Monday morning or Wednesday afternoon.', TRUE),
(1, 4, 'Monday morning works for me. Shall we say 10 AM?', TRUE),
(2, 4, 'Could you also help me with linked lists for CS220?', TRUE),
(2, 3, 'Of course! Let us set up a session for Thursday.', TRUE);

INSERT INTO sessions (id, student_id, tutor_id, subject_id, conversation_id, status, scheduled_start, scheduled_end, topic, notes) VALUES
(1, 4, 3, 1, 1, 'completed', '2026-08-10 10:00:00', '2026-08-10 11:00:00', 'Derivatives and chain rule', 'Covered derivative rules with practice problems.'),
(2, 4, 3, 3, 2, 'accepted', '2026-08-18 10:00:00', '2026-08-18 11:00:00', 'Linked lists', 'Review singly linked list operations.');

INSERT INTO evaluations (session_id, student_id, tutor_id, rating, comment) VALUES
(1, 4, 3, 5, 'Maria explains concepts very clearly and prepared great practice problems. Highly recommended!');

INSERT INTO activity_logs (user_id, action, entity_type, entity_id, details, ip_address) VALUES
(1, 'system.seed', 'database', NULL, '{"note":"Initial seed data"}' , '127.0.0.1');

-- Reset identity sequences after explicit ID inserts
SELECT setval(pg_get_serial_sequence('users', 'id'), (SELECT MAX(id) FROM users));
SELECT setval(pg_get_serial_sequence('student_profiles', 'id'), (SELECT MAX(id) FROM student_profiles));
SELECT setval(pg_get_serial_sequence('tutor_profiles', 'id'), (SELECT MAX(id) FROM tutor_profiles));
SELECT setval(pg_get_serial_sequence('subjects', 'id'), (SELECT MAX(id) FROM subjects));
SELECT setval(pg_get_serial_sequence('conversations', 'id'), (SELECT MAX(id) FROM conversations));
SELECT setval(pg_get_serial_sequence('sessions', 'id'), (SELECT MAX(id) FROM sessions));
