-- ============================================================
-- PeerLink - Peer Tutoring Platform
-- Supabase (PostgreSQL) Schema + Seed Data
-- Normalized 4-tier architecture database layer
--
-- HOW TO USE: create a Supabase project, open the SQL Editor,
-- paste this whole file and run it. It creates all tables in
-- the default `public` schema plus demo seed data.
-- ============================================================

-- Drop in dependency order so the script is re-runnable.
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS subject_requests CASCADE;
DROP TABLE IF EXISTS activity_logs CASCADE;
DROP TABLE IF EXISTS evaluations CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS conversations CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS tutor_subjects CASCADE;
DROP TABLE IF EXISTS student_subjects CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS tutor_profiles CASCADE;
DROP TABLE IF EXISTS student_profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Mimics MySQL's ON UPDATE CURRENT_TIMESTAMP for updated_at columns.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- USERS
-- ------------------------------------------------------------
CREATE TABLE users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         VARCHAR(190) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  first_name    VARCHAR(100) NOT NULL,
  last_name     VARCHAR(100) NOT NULL,
  role          TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student','tutor','faculty','admin')),
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  last_seen_at  TIMESTAMPTZ NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_users_email UNIQUE (email)
);
CREATE INDEX idx_users_role ON users (role);
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- STUDENT PROFILES
-- ------------------------------------------------------------
CREATE TABLE student_profiles (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id            BIGINT NOT NULL,
  year_level         SMALLINT NULL,
  course             VARCHAR(150) NULL,
  bio                TEXT NULL,
  age                SMALLINT NULL,
  grade_level        VARCHAR(50) NULL,
  school             VARCHAR(150) NULL,
  strand             VARCHAR(50) NULL,
  contact_no         VARCHAR(20) NULL,
  gender             VARCHAR(20) NULL,
  subjects_needed    JSONB NULL,
  learning_mode      VARCHAR(20) NULL,
  preferred_schedule JSONB NULL,
  preferred_time     VARCHAR(60) NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_student_user UNIQUE (user_id),
  CONSTRAINT fk_student_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE TRIGGER trg_student_profiles_updated_at BEFORE UPDATE ON student_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- TUTOR PROFILES
-- Availability stored as JSONB: {"Mon":["09:00-11:00"],"Tue":[...]}
-- ------------------------------------------------------------
CREATE TABLE tutor_profiles (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id            BIGINT NOT NULL,
  course             VARCHAR(150) NULL,
  max_year_level     SMALLINT NOT NULL DEFAULT 5,
  bio                TEXT NULL,
  availability       JSONB NULL,
  tags               JSONB NULL,
  age                SMALLINT NULL,
  grade_level        VARCHAR(50) NULL,
  school             VARCHAR(150) NULL,
  strand             VARCHAR(50) NULL,
  contact_no         VARCHAR(20) NULL,
  gender             VARCHAR(20) NULL,
  subjects_teach     JSONB NULL,
  learning_mode      VARCHAR(20) NULL,
  preferred_schedule JSONB NULL,
  preferred_time     VARCHAR(60) NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_tutor_user UNIQUE (user_id),
  CONSTRAINT fk_tutor_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE TRIGGER trg_tutor_profiles_updated_at BEFORE UPDATE ON tutor_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- SUBJECTS
-- ------------------------------------------------------------
CREATE TABLE subjects (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        VARCHAR(20) NOT NULL,
  name        VARCHAR(150) NOT NULL,
  description TEXT NULL,
  strand      VARCHAR(20) NULL, -- STEM / GAS / ICT / ABM / HUMSS / JHS, NULL = general
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_subjects_code UNIQUE (code)
);
CREATE TRIGGER trg_subjects_updated_at BEFORE UPDATE ON subjects FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- STUDENT SUBJECTS (subjects a student needs help with)
-- ------------------------------------------------------------
CREATE TABLE student_subjects (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_profile_id BIGINT NOT NULL,
  subject_id         BIGINT NOT NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_student_subject UNIQUE (student_profile_id, subject_id),
  CONSTRAINT fk_student_subjects_profile FOREIGN KEY (student_profile_id) REFERENCES student_profiles (id) ON DELETE CASCADE,
  CONSTRAINT fk_student_subjects_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE
);
CREATE INDEX idx_student_subjects_subject ON student_subjects (subject_id);

-- ------------------------------------------------------------
-- TUTOR SUBJECTS (subjects a tutor teaches + proficiency 1-5)
-- ------------------------------------------------------------
CREATE TABLE tutor_subjects (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_profile_id BIGINT NOT NULL,
  subject_id       BIGINT NOT NULL,
  proficiency      SMALLINT NOT NULL DEFAULT 3, -- 1-5
  rate_per_hour    NUMERIC(10,2) NOT NULL DEFAULT 100, -- peso rate per hour
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_tutor_subject UNIQUE (tutor_profile_id, subject_id),
  CONSTRAINT fk_tutor_subjects_profile FOREIGN KEY (tutor_profile_id) REFERENCES tutor_profiles (id) ON DELETE CASCADE,
  CONSTRAINT fk_tutor_subjects_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE,
  CONSTRAINT chk_tutor_proficiency CHECK (proficiency BETWEEN 1 AND 5),
  CONSTRAINT chk_tutor_rate CHECK (rate_per_hour >= 0)
);
CREATE INDEX idx_tutor_subjects_subject ON tutor_subjects (subject_id);

-- ------------------------------------------------------------
-- MATCHES (compatibility results, 0-100)
-- ------------------------------------------------------------
CREATE TABLE matches (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_profile_id   BIGINT NOT NULL,
  tutor_profile_id     BIGINT NOT NULL,
  subject_id           BIGINT NOT NULL,
  compatibility_score  NUMERIC(5,2) NOT NULL,
  score_breakdown      JSONB NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_match UNIQUE (student_profile_id, tutor_profile_id, subject_id),
  CONSTRAINT fk_matches_student FOREIGN KEY (student_profile_id) REFERENCES student_profiles (id) ON DELETE CASCADE,
  CONSTRAINT fk_matches_tutor FOREIGN KEY (tutor_profile_id) REFERENCES tutor_profiles (id) ON DELETE CASCADE,
  CONSTRAINT fk_matches_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE
);
CREATE INDEX idx_matches_student_score ON matches (student_profile_id, compatibility_score);

-- ------------------------------------------------------------
-- CONVERSATIONS (between a student user and a tutor user on a subject)
-- ------------------------------------------------------------
CREATE TABLE conversations (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  tutor_id   BIGINT NOT NULL,
  subject_id BIGINT NULL,
  deleted_by BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_conversation UNIQUE (student_id, tutor_id, subject_id),
  CONSTRAINT fk_conversations_student FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_conversations_tutor FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_conversations_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uq_conversation_no_subject ON conversations (student_id, tutor_id) WHERE subject_id IS NULL;
CREATE INDEX idx_conversations_tutor ON conversations (tutor_id);
CREATE TRIGGER trg_conversations_updated_at BEFORE UPDATE ON conversations FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- MESSAGES
-- ------------------------------------------------------------
CREATE TABLE messages (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  sender_id       BIGINT NOT NULL,
  body            TEXT NOT NULL,
  is_read         BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
  CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_messages_conversation ON messages (conversation_id, created_at);
CREATE INDEX idx_messages_sender ON messages (sender_id);

-- ------------------------------------------------------------
-- SESSIONS (tutoring sessions, full workflow)
-- ------------------------------------------------------------
CREATE TABLE sessions (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id      BIGINT NOT NULL,
  tutor_id        BIGINT NOT NULL,
  subject_id      BIGINT NOT NULL,
  conversation_id BIGINT NULL,
  status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected','cancelled','completed')),
  scheduled_start TIMESTAMPTZ NOT NULL,
  scheduled_end   TIMESTAMPTZ NOT NULL,
  topic           VARCHAR(255) NULL,
  notes           TEXT NULL,
  reject_reason   VARCHAR(300) NULL,
  cancel_reason   VARCHAR(300) NULL,
  cancelled_at    TIMESTAMPTZ NULL,
  student_complete_confirmed_at TIMESTAMPTZ NULL,
  tutor_complete_confirmed_at   TIMESTAMPTZ NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_sessions_student FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_sessions_tutor FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_sessions_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE,
  CONSTRAINT fk_sessions_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE SET NULL,
  CONSTRAINT chk_sessions_end CHECK (scheduled_end > scheduled_start)
);
CREATE INDEX idx_sessions_tutor_time ON sessions (tutor_id, status, scheduled_start);
CREATE INDEX idx_sessions_student_time ON sessions (student_id, scheduled_start);
CREATE INDEX idx_sessions_subject ON sessions (subject_id);
CREATE UNIQUE INDEX uq_sessions_active_booking ON sessions (student_id, tutor_id, subject_id) WHERE status IN ('pending','accepted');
CREATE TRIGGER trg_sessions_updated_at BEFORE UPDATE ON sessions FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- RESCHEDULE REQUESTS (request/approval flow for moving a session;
-- the schedule only changes when the other side confirms)
-- ------------------------------------------------------------
CREATE TABLE reschedule_requests (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id     BIGINT NOT NULL,
  requester_id   BIGINT NOT NULL,
  proposed_start TIMESTAMPTZ NOT NULL,
  proposed_end   TIMESTAMPTZ NOT NULL,
  reason         VARCHAR(500) NULL,
  status         TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  responded_at   TIMESTAMPTZ NULL,
  CONSTRAINT fk_reschedule_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,
  CONSTRAINT fk_reschedule_requester FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_reschedule_end CHECK (proposed_end > proposed_start)
);
CREATE INDEX idx_reschedule_session_status ON reschedule_requests (session_id, status);

-- ------------------------------------------------------------
-- PAYMENTS (student pays for an accepted session)
-- ------------------------------------------------------------
CREATE TABLE payments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  method     VARCHAR(20) NOT NULL CHECK (method IN ('gcash','maya','bank_card')),
  amount     NUMERIC(10,2) NOT NULL DEFAULT 0,
  status     TEXT NOT NULL DEFAULT 'paid' CHECK (status IN ('paid','refunded')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_payments_session UNIQUE (session_id),
  CONSTRAINT fk_payments_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_student FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_payments_student ON payments (student_id);

-- ------------------------------------------------------------
-- CONVERSATION PAYMENTS (per-conversation clearance payment:
-- student sends proof of payment inside the chat, tutor
-- accepts or rejects; if rejected the student can repay)
-- ------------------------------------------------------------
CREATE TABLE conversation_payments (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL,
  student_id      BIGINT NOT NULL,
  tutor_id        BIGINT NOT NULL,
  amount          NUMERIC(10,2) NULL,
  reference       VARCHAR(150) NULL,
  status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected')),
  reject_reason   VARCHAR(300) NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at     TIMESTAMPTZ NULL,
  CONSTRAINT fk_convpayments_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
  CONSTRAINT fk_convpayments_student FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_convpayments_tutor FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_convpayments_conversation ON conversation_payments (conversation_id, status);

-- ------------------------------------------------------------
-- EVALUATIONS (one per completed session)
-- ------------------------------------------------------------
CREATE TABLE evaluations (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  tutor_id   BIGINT NOT NULL,
  rating     SMALLINT NOT NULL,
  comment    TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_evaluation_session UNIQUE (session_id),
  CONSTRAINT fk_evaluations_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,
  CONSTRAINT fk_evaluations_student FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_evaluations_tutor FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_evaluation_rating CHECK (rating BETWEEN 1 AND 5)
);
CREATE INDEX idx_evaluations_tutor ON evaluations (tutor_id);

-- ------------------------------------------------------------
-- ACTIVITY LOGS
-- ------------------------------------------------------------
CREATE TABLE activity_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NULL,
  action      VARCHAR(100) NOT NULL,
  entity_type VARCHAR(50) NULL,
  entity_id   BIGINT NULL,
  details     JSONB NULL,
  ip_address  VARCHAR(45) NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_logs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX idx_logs_user ON activity_logs (user_id);
CREATE INDEX idx_logs_action ON activity_logs (action);
CREATE INDEX idx_logs_created ON activity_logs (created_at);

-- ------------------------------------------------------------
-- SUBJECT REQUESTS (tutors request a new subject; admin approves
-- and assigns it to the tutor's preset "Subjects I Teach" list)
-- ------------------------------------------------------------
CREATE TABLE subject_requests (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_id      BIGINT NOT NULL,
  code          VARCHAR(20) NOT NULL,
  name          VARCHAR(150) NOT NULL,
  description   TEXT NULL,
  proficiency   SMALLINT NOT NULL DEFAULT 3,
  strand        VARCHAR(20) NULL,
  status        TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at   TIMESTAMPTZ NULL,
  CONSTRAINT uq_subject_request UNIQUE (tutor_id, code),
  CONSTRAINT fk_subject_requests_tutor FOREIGN KEY (tutor_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_subject_request_proficiency CHECK (proficiency BETWEEN 1 AND 5)
);
CREATE INDEX idx_subject_requests_status ON subject_requests (status);

-- ============================================================
-- SEED DATA
-- Default passwords: Admin@123 / Faculty@123 / Tutor@123 / Student@123
-- Hashes generated with bcryptjs (cost 10)
-- Only demo accounts + preset profiles are seeded.
-- No sessions, messages, conversations, matches, evaluations,
-- subjects or activity logs — add those from the app itself.
-- ============================================================

INSERT INTO users (id, email, password_hash, first_name, last_name, role, is_active) VALUES
(1, 'admin@peerlink.edu', '$2a$10$vvDNXhEYATRXuM6NXzQW.eweNMp6/DT4iri5L6FyLcQG3ZUHzijgi', 'Alex', 'Admin', 'admin', TRUE),
(2, 'faculty@peerlink.edu', '$2a$10$JDusT272YLpZvBJ/CRJM0u0NnxGraIk0QqtNtms78LYSJzTipY56i', 'Dana', 'Faculty', 'faculty', TRUE),
(3, 'maria@peerlink.edu', '$2a$10$oqZpYzmn5EjTMD0mpfSbk.3YFAsP3MU.zcgnc8ozv2P8qMKam7h5u', 'Maria', 'Tutor', 'tutor', TRUE),
(4, 'student@peerlink.edu', '$2a$10$sxsfR9PejLT4wmo1A6i2Uer0XPVLGpd2RGZD6ptBm2lB9HBQ8Vt8K', 'Juswa', 'Student', 'student', TRUE),
(5, 'gerome@peerlink.edu', '$2a$10$oqZpYzmn5EjTMD0mpfSbk.3YFAsP3MU.zcgnc8ozv2P8qMKam7h5u', 'Gerome', 'Sanchez', 'tutor', TRUE),
(6, 'kiel@peerlink.edu', '$2a$10$oqZpYzmn5EjTMD0mpfSbk.3YFAsP3MU.zcgnc8ozv2P8qMKam7h5u', 'Kiel', 'Reyes', 'tutor', TRUE),
(7, 'mike.chen@peerlink.edu', '$2a$10$sxsfR9PejLT4wmo1A6i2Uer0XPVLGpd2RGZD6ptBm2lB9HBQ8Vt8K', 'Mike', 'Chen', 'student', TRUE);

INSERT INTO student_profiles (id, user_id, year_level, course, bio) VALUES
(1, 4, 2, 'Computer Science', 'Second year CS student looking for help with math and programming.'),
(2, 7, 1, 'Computer Science', 'Freshman CS student, struggling with calculus.');

INSERT INTO tutor_profiles (id, user_id, course, max_year_level, bio, availability) VALUES
(1, 3, 'Computer Science', 4, 'Senior CS student. Strong in math and programming, patient with beginners.', '{"Mon":["09:00-12:00","15:00-17:00"],"Tue":["10:00-13:00"],"Wed":["09:00-11:00","14:00-16:00"],"Thu":["10:00-12:00"],"Fri":["09:00-12:00"]}'),
(2, 5, 'Mathematics', 5, 'History and mathematics tutor. Clear, structured review sessions with guides.', '{"Mon":["09:00-11:00"],"Tue":["14:00-17:00"],"Wed":["09:00-11:00","15:00-17:00"],"Thu":["14:00-16:00"],"Fri":["13:00-17:00"]}'),
(3, 6, 'Networking', 5, 'Networking specialist. TCP/IP, routing, and subnetting made simple.', '{"Mon":["13:00-16:00"],"Tue":["09:00-11:00"],"Wed":["13:00-15:00"],"Thu":["15:00-17:00"],"Fri":["09:00-12:00"]}');

INSERT INTO subjects (id, code, name, description, strand) VALUES
(1, 'MATH101', 'Calculus I', 'Limits, derivatives, and integrals of single-variable functions.', 'STEM'),
(2, 'MATH210', 'Linear Algebra', 'Vectors, matrices, eigenvalues, and linear transformations.', 'STEM'),
(3, 'CS220', 'Data Structures', 'Stacks, queues, trees, graphs, and algorithmic analysis.', 'ICT'),
(4, 'CS330', 'Web Development', 'HTML, CSS, JavaScript, and modern web frameworks.', 'ICT'),
(5, 'ENG110', 'English Composition', 'Academic writing, essays, and research papers.', NULL),
(6, 'PHYS101', 'Physics I', 'Mechanics: kinematics, forces, energy, and momentum.', 'STEM'),
(7, 'CS240', 'Database Systems', 'SQL, database design, normalization, and transactions.', 'ICT'),
(8, 'STAT150', 'Statistics', 'Descriptive statistics, probability, and hypothesis testing.', NULL),
(9, 'HIST101', 'History', 'World history, Philippine history, and social studies.', 'HUMSS'),
(10, 'NET101', 'Computer Networking', 'OSI model, TCP/IP, routing, and network configuration.', 'ICT'),
(11, 'PRG101', 'Programming Fundamentals', 'Logic, control structures, functions, and problem solving.', 'ICT'),
(12, 'BIO101', 'Biology', 'Cell biology, genetics, and human anatomy.', 'STEM'),
(13, 'CS230', 'Embedded Systems', 'Microcontrollers, sensors, and embedded C programming.', 'ICT'),
(14, 'GEN101', 'Oral Communication', 'Speech, listening and interpersonal communication skills.', NULL),
(15, 'GEN102', 'Reading and Writing', 'Critical reading strategies and academic writing skills.', NULL),
(16, 'GEN103', 'Filipino Language and Literature', 'Komunikasyon at pananaliksik sa wika at kulturang Filipino.', NULL),
(17, 'GEN104', '21st Century Literature', 'Literature from the Philippines and around the world.', NULL),
(18, 'GEN105', 'Contemporary Philippine Arts', 'Contemporary art forms and practices from the regions.', NULL),
(19, 'GEN106', 'Media and Information Literacy', 'Understanding media, information sources, and digital literacy.', NULL),
(20, 'GEN107', 'General Mathematics', 'Functions, logarithms, business math and logic.', NULL),
(21, 'GEN109', 'Earth and Life Science', 'Earth systems, geology, and life processes.', NULL),
(22, 'GEN110', 'Physical Science', 'Chemistry and physics concepts in everyday life.', NULL),
(23, 'GEN111', 'Personal Development', 'Self-awareness, emotional intelligence, and career planning.', NULL),
(24, 'GEN112', 'Understanding Culture, Society and Politics', 'Culture, society, and political structures.', NULL),
(25, 'GEN113', 'Introduction to the Philosophy of the Human Person', 'Philosophical reflection on human existence.', NULL),
(26, 'GEN114', 'Physical Education and Health', 'Fitness, sports, and healthy lifestyle practices.', NULL),
(27, 'GEN115', 'Practical Research 1', 'Qualitative research methods and writing.', NULL),
(28, 'GEN116', 'Practical Research 2', 'Quantitative research methods and statistical treatment.', NULL),
(29, 'GEN117', 'Inquiries, Investigation and Immersion', 'Immersive research experience and reporting.', NULL),
(30, 'GEN118', 'Empowerment Technologies', 'ICT tools, productivity software, and online safety.', NULL),
(31, 'GEN119', 'Entrepreneurship', 'Business idea development and small business planning.', NULL),
(32, 'STEM09', 'Pre-Calculus', 'Trigonometry, conic sections, and series.', 'STEM'),
(33, 'STEM10', 'Basic Calculus', 'Limits, derivatives and integrals in the SHS curriculum.', 'STEM'),
(34, 'STEM11', 'General Biology 1', 'Cell biology and life processes.', 'STEM'),
(35, 'STEM12', 'General Chemistry 1', 'Atomic structure, chemical bonding, and stoichiometry.', 'STEM'),
(36, 'STEM13', 'General Chemistry 2', 'Thermodynamics, kinetics, and organic chemistry.', 'STEM'),
(37, 'STEM14', 'General Physics 1', 'Mechanics, waves, and heat.', 'STEM'),
(38, 'STEM15', 'General Physics 2', 'Electricity, magnetism, optics, and modern physics.', 'STEM'),
(39, 'STEM16', 'Research Project / Capstone', 'Independent STEM research culminating in a capstone project.', 'STEM'),
(40, 'ABM01', 'Organization and Management', 'Management theories, functions, and organizational structures.', 'ABM'),
(41, 'ABM02', 'Business Mathematics', 'Profit and loss, ratios, and business computations.', 'ABM'),
(42, 'ABM03', 'Principles of Marketing', 'Marketing concepts, consumer behavior, and branding.', 'ABM'),
(43, 'ABM04', 'Fundamentals of Accountancy, Business and Management 1', 'Accounting basics, journal entries, and financial statements.', 'ABM'),
(44, 'ABM05', 'Fundamentals of Accountancy, Business and Management 2', 'Advanced accounting cycles and business management.', 'ABM'),
(45, 'ABM06', 'Applied Economics', 'Economic principles applied to current issues.', 'ABM'),
(46, 'ABM07', 'Business Ethics and Social Responsibility', 'Ethical decision-making in business.', 'ABM'),
(47, 'ABM08', 'Business Finance', 'Financial management, risk, and investment basics.', 'ABM'),
(48, 'HUMSS01', 'Philippine Politics and Governance', 'Philippine government structure and political dynamics.', 'HUMSS'),
(49, 'HUMSS02', 'Trends, Networks, and Critical Thinking', 'Trend analysis, networks, and critical thinking skills.', 'HUMSS'),
(50, 'HUMSS03', 'Community Engagement, Solidarity and Citizenship', 'Community dynamics and civic participation.', 'HUMSS'),
(51, 'HUMSS04', 'Discipline and Ideas in the Social Sciences', 'Foundations of the social science disciplines.', 'HUMSS'),
(52, 'HUMSS05', 'Disciplines and Ideas in the Applied Social Sciences', 'Applied fields: counseling, social work, and communication.', 'HUMSS'),
(53, 'HUMSS06', 'Creative Writing', 'Poetry, fiction, and drama writing practice.', 'HUMSS'),
(54, 'HUMSS07', 'Creative Nonfiction', 'Literary journalism, memoir, and personal essays.', 'HUMSS'),
(55, 'HUMSS08', 'Introduction to World Religions and Belief Systems', 'Comparative study of major world religions.', 'HUMSS'),
(56, 'GAS01', 'Earth Science', 'Geology, meteorology, and environmental science.', 'GAS'),
(57, 'GAS02', 'Economics', 'Microeconomics, macroeconomics, and economic systems.', 'GAS'),
(58, 'GAS03', 'English for Academic and Professional Purposes', 'Academic language and workplace communication.', 'GAS'),
(59, 'ICT01', 'Computer System Servicing', 'Hardware assembly, maintenance, and system configuration.', 'ICT'),
(60, 'ICT02', 'Animation', '2D/3D animation principles and production.', 'ICT');

-- Preset "Subjects I Teach" — tutors cannot change this list
-- themselves; they may only REQUEST a new subject (see
-- subject_requests) which an admin approves and assigns here.
INSERT INTO tutor_subjects (tutor_profile_id, subject_id, proficiency) VALUES
(1, 1, 5), (1, 3, 5), (1, 5, 4),
(2, 1, 4), (2, 9, 5),
(3, 10, 5);

-- Reset identity sequences after explicit ID inserts
SELECT setval(pg_get_serial_sequence('users', 'id'), (SELECT MAX(id) FROM users));
SELECT setval(pg_get_serial_sequence('student_profiles', 'id'), (SELECT MAX(id) FROM student_profiles));
SELECT setval(pg_get_serial_sequence('tutor_profiles', 'id'), (SELECT MAX(id) FROM tutor_profiles));
SELECT setval(pg_get_serial_sequence('subjects', 'id'), (SELECT MAX(id) FROM subjects));
SELECT setval(pg_get_serial_sequence('tutor_subjects', 'id'), (SELECT MAX(id) FROM tutor_subjects));

-- ============================================================
-- MIGRATIONS (for databases created from an older version)
-- Run only if the columns above are missing in your database.
-- The statements are idempotent, so they are safe to re-run.
-- ============================================================
ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS age SMALLINT NULL;
ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS grade_level VARCHAR(50) NULL;
ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS school VARCHAR(150) NULL;
ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS strand VARCHAR(50) NULL;
ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS subjects_needed JSONB NULL;
ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS learning_mode VARCHAR(20) NULL;
ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS preferred_schedule JSONB NULL;
ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS preferred_time VARCHAR(60) NULL;

ALTER TABLE tutor_profiles ADD COLUMN IF NOT EXISTS tags JSONB NULL;
ALTER TABLE tutor_profiles ADD COLUMN IF NOT EXISTS age SMALLINT NULL;
ALTER TABLE tutor_profiles ADD COLUMN IF NOT EXISTS grade_level VARCHAR(50) NULL;
ALTER TABLE tutor_profiles ADD COLUMN IF NOT EXISTS school VARCHAR(150) NULL;
ALTER TABLE tutor_profiles ADD COLUMN IF NOT EXISTS strand VARCHAR(50) NULL;
ALTER TABLE tutor_profiles ADD COLUMN IF NOT EXISTS subjects_teach JSONB NULL;
ALTER TABLE tutor_profiles ADD COLUMN IF NOT EXISTS learning_mode VARCHAR(20) NULL;
ALTER TABLE tutor_profiles ADD COLUMN IF NOT EXISTS preferred_schedule JSONB NULL;
ALTER TABLE tutor_profiles ADD COLUMN IF NOT EXISTS preferred_time VARCHAR(60) NULL;

ALTER TABLE tutor_subjects ADD COLUMN IF NOT EXISTS rate_per_hour NUMERIC(10,2) NOT NULL DEFAULT 100;
